services:
  - type: web
    name: sistema-materiais
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
    healthCheckPath: /

